# Generated by Django 3.2.3 on 2021-05-14 18:07

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.CharField(default=game.models.generate_unique_game_code, max_length=8),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_code',
            field=models.CharField(default=game.models.generate_unique_player_code, max_length=8),
        ),
    ]
