# Generated by Django 3.2.3 on 2021-05-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210514_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_name',
        ),
    ]
