# Generated by Django 3.2.3 on 2021-05-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210514_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='room_name',
            new_name='game',
        ),
    ]
