# Generated by Django 3.2.3 on 2021-05-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_room_name_player_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='p1_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p2_name',
        ),
        migrations.AddField(
            model_name='game',
            name='round_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
