# Generated by Django 3.2.3 on 2021-05-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210516_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='winner',
            new_name='p',
        ),
    ]
