# Generated by Django 3.2.3 on 2021-05-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_winner_game_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round_no',
            field=models.IntegerField(default=1),
        ),
    ]
