# Generated by Django 3.2.3 on 2021-05-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_round_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round_no',
            field=models.IntegerField(default=0),
        ),
    ]
