# Generated by Django 3.2.3 on 2021-05-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_round_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='word',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
